routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('localization/{locale}', function ($locale) {
	\Session::put('locale', $locale);
	return redirect()->back();
});

Route::get('/clear-all', function () {
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('route:clear');
    Artisan::call('view:clear');
    exec('composer dump-autoload');
});

Route::group(['middleware' => 'auth'], function () {

	Route::get('/', 'HomeController@index')->name('home');
	Route::resources([
	    'employees' => 'EmployeeController'
	]);

	Route::resources([
	    'companies' => 'CompanyController'
	]);
});

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Controllers\_dev\MailController;
use App\Http\Requests\CompanyStoreRequest;
use App\Model\Company;
use Carbon\Carbon;
use Exception;
use File;
use Illuminate\Http\Request;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::paginate(10);

        return view('companies.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyStoreRequest $request)
    {
        try {

            $data = $request->validated();

            $file     = $request->logo;
            $fileName = md5(Carbon::now()) . $file->getClientOriginalName();
            $file->move(storage_path('app/public/logo/'), $fileName);

            Company::create(array_merge($data, ['logo' => $fileName]));
            $emailDataArr = [
                'title'   => "A new company is been created",
                'content' => 'Hello, <br>A new company is been created with this email account.',

                'subject' => "A new company is been created",
                'from'    => [
                    'email' => 'info@testtool.ok',
                    'name'  => 'Som- GoodDev',
                ],
                'to'      => [
                    'email' => $data['email'],
                    'name'  => $data['name'],
                ],
                'view'    => 'manage.email',
            ];

            MailController::firemail($emailDataArr);

            return redirect()->route('companies.index')
                ->with('success_message', trans('companies.model_was_added'));

        } catch (Exception $exception) {

            return back()->withInput()
                ->withErrors(['unexpected_error' => trans('companies.unexpected_error')]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Company::findOrFail($id);

        return view('companies.show', compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::findOrFail($id);

        return view('companies.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyStoreRequest $request, $id)
    {
        try {

            $data = $request->validated();

            $company = Company::findOrFail($id);
            $logoArr = [];
            if (!empty($request->logo)) {

                $file     = $request->logo;
                $fileName = md5(Carbon::now()) . $file->getClientOriginalName();
                $file->move(storage_path('app/public/logo/'), $fileName);
                $logoArr = ['logo' => $fileName];

                if ($company && $company->logo) {

                    File::delete(storage_path('app/public/logo/' . $company->logo));
                }
            }

            $company->update(array_merge($data, $logoArr));
            $emailDataArr = [
                'title'   => "Company is been updated",
                'content' => 'Hello, <br>Company is been updated with this email account.',

                'subject' => "Company is been updated",
                'from'    => [
                    'email' => 'info@testtool.ok',
                    'name'  => 'Som- GoodDev',
                ],
                'to'      => [
                    'email' => $data['email'],
                    'name'  => $data['name'],
                ],
                'view'    => 'manage.email',
            ];

            MailController::firemail($emailDataArr);

            return redirect()->route('companies.index')
                ->with('success_message', trans('companies.model_was_updated'));

        } catch (Exception $exception) {

            return back()->withInput()
                ->withErrors(['unexpected_error' => trans('companies.unexpected_error')]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $company = Company::findOrFail($id);
            $company->delete();

            return redirect()->route('companies.index')
                ->with('success_message', trans('companies.model_was_deleted'));

        } catch (Exception $exception) {

            return back()->withInput()
                ->withErrors(['unexpected_error' => trans('companies.unexpected_error')]);
        }
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="panel panel-default">

        <div class="panel-heading clearfix">
            
            <span class="pull-left">
                <h4 class="mt-5 mb-5">{{ trans('companies.create') }}</h4>
            </span>

            <div class="btn-group btn-group-sm pull-right" role="group">
                <a href="{{ route('companies.index') }}" class="btn btn-primary" title="{{ trans('companies.show_all') }}">
                    <i class="fa fa-list-ul" aria-hidden="true"></i>
                </a>
            </div>

        </div>

        <div class="panel-body">
        
            @if ($errors->any())
                <ul class="alert alert-danger">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif

            <form method="POST" action="{{ route('companies.store') }}" accept-charset="UTF-8" id="create_post_form" name="create_post_form" class="form-horizontal" enctype="multipart/form-data">
            {{ csrf_field() }}
            @include ('companies.form', [
                                        'company' => null,
                                      ])

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input class="btn btn-primary" type="submit" value="{{ trans('companies.add') }}">
                    </div>
                </div>

            </form>

        </div>
    </div>

@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="panel panel-default">
  
        <div class="panel-heading clearfix">

            <div class="pull-left">
                <h4 class="mt-5 mb-5">{{ trans('companies.edit') }}</h4>
            </div>
            <div class="btn-group btn-group-sm pull-right" role="group">

                <a href="{{ route('companies.index') }}" class="btn btn-primary" title="{{ trans('companies.show_all') }}">
                    <i class="fa fa-list-ul" aria-hidden="true"></i>
                </a>

                <a href="{{ route('companies.create') }}" class="btn btn-success" title="{{ trans('companies.create') }}">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                </a>

            </div>
        </div>

        <div class="panel-body">

            @if ($errors->any())
                <ul class="alert alert-danger">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif

            <form method="POST" action="{{ route('companies.update', $company->id) }}" id="edit_company_form" name="edit_company_form" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
            {{ csrf_field() }}
            <input name="_method" type="hidden" value="PUT">
            @include ('companies.form', [
                                        'company' => $company,
                                      ])

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input class="btn btn-primary" type="submit" value="{{ trans('companies.update') }}">
                    </div>
                </div>
            </form>

        </div>
    </div>

@endsection

resources/views/companies/form.blade.php
<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
    <label for="name" class="col-md-2 control-label">{{ trans('companies.name') }}</label>
    <div class="col-md-10">
        <input class="form-control" name="name" type="text" id="name" value="{{ old('name', optional($company)->name) }}" minlength="1" maxlength="255" placeholder="{{ trans('companies.name__placeholder') }}">
        {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
    <label for="email" class="col-md-2 control-label">{{ trans('companies.email') }}</label>
    <div class="col-md-10">
        <input class="form-control" name="email" type="email" id="email" value="{{ old('email', optional($company)->email) }}" minlength="1" maxlength="255" placeholder="{{ trans('companies.email__placeholder') }}">
        {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('logo') ? 'has-error' : '' }}">
    <label for="logo" class="col-md-2 control-label">{{ trans('companies.logo') }}</label>
    <div class="col-md-10">
        @if(optional($company)->logo)
            <img src="{{ asset('logo/'.optional($company)->logo) }}" width="50" />
            <br>
        @endif
        <input class="form-control" name="logo" type="file" id="logo" value="{{ old('logo', optional($company)->logo) }}" minlength="1" maxlength="255" placeholder="{{ trans('companies.logo__placeholder') }}">
        {!! $errors->first('logo', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('website') ? 'has-error' : '' }}">
    <label for="website" class="col-md-2 control-label">{{ trans('companies.website') }}</label>
    <div class="col-md-10">
        <input class="form-control" name="website" type="text" id="website" value="{{ old('website', optional($company)->website) }}" minlength="1" maxlength="255" placeholder="{{ trans('companies.website__placeholder') }}">
        {!! $errors->first('website', '<p class="help-block">:message</p>') !!}
    </div>
</div>

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('content')

    @if(Session::has('success_message'))
        <div class="alert alert-success">
        
            {!! session('success_message') !!}

            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                <span aria-hidden="true">&times;</span>
            </button>

        </div>
    @endif

    <div class="panel panel-default">

        <div class="panel-heading clearfix">

            <div class="pull-left">
                <h4 class="mt-5 mb-5">{{ trans('companies.model_plural') }}</h4>
            </div>

            <div class="btn-group btn-group-sm pull-right" role="group">
                <a href="{{ route('companies.create') }}" class="btn btn-success" title="{{ trans('companies.create') }}">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                </a>
            </div>

        </div>
        
        @if(count($companies) == 0)
            <div class="panel-body text-center">
                <h4>{{ trans('companies.none_available') }}</h4>
            </div>
        @else
        <div class="panel-body panel-body-with-table">
            <div class="table-responsive">

                <table class="table table-striped ">
                    <thead>
                        <tr>
                            <th>{{ trans('companies.name') }}</th>
                            <th>{{ trans('companies.logo') }}</th>
                            <th>{{ trans('companies.email') }}</th>
                            <th>{{ trans('companies.website') }}</th>

                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($companies as $company)
                        <tr>
                            <td>{{ $company->name }}</td>
                            <td><img src="{{ asset('logo/'.$company->logo) }}" width="50" /></td>
                            <td>{{ $company->email }}</td>
                            <td>{{ $company->website }}</td>

                            <td>

                                <form method="company" action="{!! route('companies.destroy', $company->id) !!}" accept-charset="UTF-8">
                                <input name="_method" value="DELETE" type="hidden">
                                {{ csrf_field() }}

                                    <div class="btn-group btn-group-xs pull-right" role="group">
                                        <a href="{{ route('companies.show', $company->id ) }}" class="btn btn-info" title="{{ trans('companies.show') }}">
                                            <span class="fa fa-eye" aria-hidden="true"></span>
                                        </a>
                                        <a href="{{ route('companies.edit', $company->id ) }}" class="btn btn-primary" title="{{ trans('companies.edit') }}">
                                            <span class="fa fa-edit" aria-hidden="true"></span>
                                        </a>

                                        <button type="submit" class="btn btn-danger" title="{{ trans('companies.delete') }}" >
                                            <span class="fa fa-trash" aria-hidden="true"></span>
                                        </button>
                                    </div>

                                </form>
                                
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>

        <div class="panel-footer">
            {!! $companies->render() !!}
        </div>
        
        @endif
    
    </div>
@endsection

resources/views/companies/show.blade.php
@extends('layouts.app')

@section('content')

<div class="panel panel-default">
    <div class="panel-heading clearfix">

        <span class="pull-left">
            <h4 class="mt-5 mb-5">{{ trans('companies.show') }}</h4>
        </span>

        <div class="pull-right">

            <form method="POST" action="{!! route('companies.destroy', $company->id) !!}" accept-charset="UTF-8">
            <input name="_method" value="DELETE" type="hidden">
            {{ csrf_field() }}
                <div class="btn-group btn-group-sm" role="group">
                    <a href="{{ route('companies.index') }}" class="btn btn-primary" title="{{ trans('companies.show_all') }}">
                        <span class="fa fa-list-ul" aria-hidden="true"></span>
                    </a>

                    <a href="{{ route('companies.create') }}" class="btn btn-success" title="{{ trans('companies.create') }}">
                        <span class="fa fa-plus" aria-hidden="true"></span>
                    </a>
                    
                    <a href="{{ route('companies.edit', $company->id ) }}" class="btn btn-primary" title="{{ trans('companies.edit') }}">
                        <span class="fa fa-edit" aria-hidden="true"></span>
                    </a>

                    <button type="submit" class="btn btn-danger" title="{{ trans('companies.delete') }}" onclick="return confirm(&quot;{{ trans('companies.confirm_delete') }}?&quot;)">
                        <span class="fa fa-trash" aria-hidden="true"></span>
                    </button>
                </div>
            </form>

        </div>

    </div>

    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>{{ trans('companies.name') }}</dt>
            <dd>{{ $company->name }}</dd>

            <dt>{{ trans('companies.logo') }}</dt>
            <dd>{{ $company->logo }}</dd>

            <dt>{{ trans('companies.email') }}</dt>
            <dd>{{ $company->email }}</dd>

            <dt>{{ trans('companies.website') }}</dt>
            <dd>{{ $company->website }}</dd>

        </dl>

    </div>
</div>

@endsection