routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('localization/{locale}', function ($locale) {
	\Session::put('locale', $locale);
	return redirect()->back();
});

Route::get('/clear-all', function () {
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('route:clear');
    Artisan::call('view:clear');
    exec('composer dump-autoload');
});

Route::group(['middleware' => 'auth'], function () {

	Route::get('/', 'HomeController@index')->name('home');
	Route::resources([
	    'employees' => 'EmployeeController'
	]);

	Route::resources([
	    'companies' => 'CompanyController'
	]);
});

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests\EmployeeStoreRequest;
use App\Model\Employee;
use App\Model\Company;
use Exception;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::paginate(10);

        return view('employees.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::get();
        return view('employees.create',compact('companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeStoreRequest $request)
    {
        try {
            $data = $request->validated();
            Employee::create($data);

            return redirect()->route('employees.index')
                ->with('success_message', trans('employees.model_was_added'));

        } catch (Exception $exception) {

            return back()->withInput()
                ->withErrors(['unexpected_error' => trans('employees.unexpected_error')]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $employee = Employee::findOrFail($id);
        return view('employees.show', compact('employee'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $companies = Company::get();
        $employee = Employee::findOrFail($id);

        return view('employees.edit', compact('employee','companies'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeStoreRequest $request, $id)
    {
        try {

            $data = $request->validated();

            $employee = Employee::findOrFail($id);
            $employee->update($data);

            return redirect()->route('employees.index')
                ->with('success_message', trans('employees.model_was_updated'));

        } catch (Exception $exception) {

            return back()->withInput()
                ->withErrors(['unexpected_error' => trans('employees.unexpected_error')]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $employee = Employee::findOrFail($id);
            $employee->delete();

            return redirect()->route('employees.index')
                ->with('success_message', trans('employees.model_was_deleted'));

        } catch (Exception $exception) {

            return back()->withInput()
                ->withErrors(['unexpected_error' => trans('employees.unexpected_error')]);
        }
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="panel panel-default">

        <div class="panel-heading clearfix">
            
            <span class="pull-left">
                <h4 class="mt-5 mb-5">{{ trans('employees.create') }}</h4>
            </span>

            <div class="btn-group btn-group-sm pull-right" role="group">
                <a href="{{ route('employees.index') }}" class="btn btn-primary" title="{{ trans('employees.show_all') }}">
                    <i class="fa fa-list-ul" aria-hidden="true"></i>
                </a>
            </div>

        </div>

        <div class="panel-body">
        
            @if ($errors->any())
                <ul class="alert alert-danger">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif

            <form method="POST" action="{{ route('employees.store') }}" accept-charset="UTF-8" id="create_post_form" name="create_post_form" class="form-horizontal">
            {{ csrf_field() }}
            @include ('employees.form', [
                                        'employee' => null,
                                      ])

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input class="btn btn-primary" type="submit" value="{{ trans('employees.add') }}">
                    </div>
                </div>

            </form>

        </div>
    </div>

@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="panel panel-default">
  
        <div class="panel-heading clearfix">

            <div class="pull-left">
                <h4 class="mt-5 mb-5">{{ trans('employees.edit') }}</h4>
            </div>
            <div class="btn-group btn-group-sm pull-right" role="group">

                <a href="{{ route('employees.index') }}" class="btn btn-primary" title="{{ trans('employees.show_all') }}">
                    <i class="fa fa-list-ul" aria-hidden="true"></i>
                </a>

                <a href="{{ route('employees.create') }}" class="btn btn-success" title="{{ trans('employees.create') }}">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                </a>

            </div>
        </div>

        <div class="panel-body">

            @if ($errors->any())
                <ul class="alert alert-danger">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif

            <form method="POST" action="{{ route('employees.update', $employee->id) }}" id="edit_employee_form" name="edit_employee_form" accept-charset="UTF-8" class="form-horizontal">
            {{ csrf_field() }}
            <input name="_method" type="hidden" value="PUT">
            @include ('employees.form', [
                                        'employee' => $employee,
                                      ])

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input class="btn btn-primary" type="submit" value="{{ trans('employees.update') }}">
                    </div>
                </div>
            </form>

        </div>
    </div>

@endsection

resources/views/employees/form.blade.php
<div class="form-group {{ $errors->has('first_name') ? 'has-error' : '' }}">
    <label for="first_name" class="col-md-2 control-label">{{ trans('employees.first_name') }}</label>
    <div class="col-md-10">
        <input class="form-control" name="first_name" type="text" id="first_name" value="{{ old('first_name', optional($employee)->first_name) }}" minlength="1" maxlength="255" placeholder="{{ trans('employees.first_name__placeholder') }}">
        {!! $errors->first('first_name', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('last_name') ? 'has-error' : '' }}">
    <label for="last_name" class="col-md-2 control-label">{{ trans('employees.last_name') }}</label>
    <div class="col-md-10">
        <input class="form-control" name="last_name" type="text" id="last_name" value="{{ old('last_name', optional($employee)->last_name) }}" minlength="1" maxlength="255" placeholder="{{ trans('employees.last_name__placeholder') }}">
        {!! $errors->first('last_name', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
    <label for="email" class="col-md-2 control-label">{{ trans('employees.email') }}</label>
    <div class="col-md-10">
        <input class="form-control" name="email" type="email" id="email" value="{{ old('email', optional($employee)->email) }}" minlength="1" maxlength="255" placeholder="{{ trans('employees.email__placeholder') }}">
        {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('phone') ? 'has-error' : '' }}">
    <label for="phone" class="col-md-2 control-label">{{ trans('employees.phone') }}</label>
    <div class="col-md-10">
        <input class="form-control" name="phone" type="text" id="phone" value="{{ old('phone', optional($employee)->phone) }}" minlength="1" maxlength="255" placeholder="{{ trans('employees.phone__placeholder') }}">
        {!! $errors->first('phone', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('company_id') ? 'has-error' : '' }}">
    <label for="company_id" class="col-md-2 control-label">{{ trans('employees.company_id') }}</label>
    <div class="col-md-10">
        <select class="form-control" name="company_id" id="company_id">
            <option value="0">{{ trans('employees.company_id__placeholder') }}</option>
            @foreach($companies as $company)
                <option value="{!! $company->id !!}" {!! (old('company_id', optional($employee)->company_id)==$company->id) ? 'selected="selected"' : '' !!}>{!! $company->name !!} ({!! $company->email !!})</option>
            @endforeach
        </select>
        {!! $errors->first('company_id', '<p class="help-block">:message</p>') !!}
    </div>
</div>

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('content')

    @if(Session::has('success_message'))
        <div class="alert alert-success">
        
            {!! session('success_message') !!}

            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                <span aria-hidden="true">&times;</span>
            </button>

        </div>
    @endif

    <div class="panel panel-default">

        <div class="panel-heading clearfix">

            <div class="pull-left">
                <h4 class="mt-5 mb-5">{{ trans('employees.model_plural') }}</h4>
            </div>

            <div class="btn-group btn-group-sm pull-right" role="group">
                <a href="{{ route('employees.create') }}" class="btn btn-success" title="{{ trans('employees.create') }}">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                </a>
            </div>

        </div>
        
        @if(count($employees) == 0)
            <div class="panel-body text-center">
                <h4>{{ trans('employees.none_available') }}</h4>
            </div>
        @else
        <div class="panel-body panel-body-with-table">
            <div class="table-responsive">

                <table class="table table-striped ">
                    <thead>
                        <tr>
                            <th>{{ trans('employees.first_name') }}</th>
                            <th>{{ trans('employees.last_name') }}</th>
                            <th>{{ trans('employees.email') }}</th>
                            <th>{{ trans('employees.phone') }}</th>

                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($employees as $employee)
                        <tr>
                            <td>{{ $employee->first_name }}</td>
                            <td>{{ $employee->last_name }}</td>
                            <td>{{ $employee->email }}</td>
                            <td>{{ $employee->phone }}</td>

                            <td>

                                <form method="employee" action="{!! route('employees.destroy', $employee->id) !!}" accept-charset="UTF-8">
                                <input name="_method" value="DELETE" type="hidden">
                                {{ csrf_field() }}

                                    <div class="btn-group btn-group-xs pull-right" role="group">
                                        <a href="{{ route('employees.show', $employee->id ) }}" class="btn btn-info" title="{{ trans('employees.show') }}">
                                            <span class="fa fa-eye" aria-hidden="true"></span>
                                        </a>
                                        <a href="{{ route('employees.edit', $employee->id ) }}" class="btn btn-primary" title="{{ trans('employees.edit') }}">
                                            <span class="fa fa-edit" aria-hidden="true"></span>
                                        </a>

                                        <button type="submit" class="btn btn-danger" title="{{ trans('employees.delete') }}" >
                                            <span class="fa fa-trash" aria-hidden="true"></span>
                                        </button>
                                    </div>

                                </form>
                                
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>

        <div class="panel-footer">
            {!! $employees->render() !!}
        </div>
        
        @endif
    
    </div>
@endsection

resources/views/employees/show.blade.php
@extends('layouts.app')

@section('content')

<div class="panel panel-default">
    <div class="panel-heading clearfix">

        <span class="pull-left">
            <h4 class="mt-5 mb-5">{{ trans('employees.show') }}</h4>
        </span>

        <div class="pull-right">

            <form method="POST" action="{!! route('employees.destroy', $employee->id) !!}" accept-charset="UTF-8">
            <input name="_method" value="DELETE" type="hidden">
            {{ csrf_field() }}
                <div class="btn-group btn-group-sm" role="group">
                    <a href="{{ route('employees.index') }}" class="btn btn-primary" title="{{ trans('employees.show_all') }}">
                        <span class="fa fa-list-ul" aria-hidden="true"></span>
                    </a>

                    <a href="{{ route('employees.create') }}" class="btn btn-success" title="{{ trans('employees.create') }}">
                        <span class="fa fa-plus" aria-hidden="true"></span>
                    </a>
                    
                    <a href="{{ route('employees.edit', $employee->id ) }}" class="btn btn-primary" title="{{ trans('employees.edit') }}">
                        <span class="fa fa-edit" aria-hidden="true"></span>
                    </a>

                    <button type="submit" class="btn btn-danger" title="{{ trans('employees.delete') }}" onclick="return confirm(&quot;{{ trans('employees.confirm_delete') }}?&quot;)">
                        <span class="fa fa-trash" aria-hidden="true"></span>
                    </button>
                </div>
            </form>

        </div>

    </div>

    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>{{ trans('employees.first_name') }}</dt>
            <dd>{{ $employee->first_name }}</dd>

            <dt>{{ trans('employees.last_name') }}</dt>
            <dd>{{ $employee->last_name }}</dd>

            <dt>{{ trans('employees.email') }}</dt>
            <dd>{{ $employee->email }}</dd>

            <dt>{{ trans('employees.phone') }}</dt>
            <dd>{{ $employee->phone }}</dd>

            <dt>{{ trans('employees.company_id') }}</dt>
            <dd>{{ $employee->getcompany->name }}-{!! $employee->getcompany->email !!}</dd>

        </dl>

    </div>
</div>

@endsection