routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('localization/{locale}', function ($locale) {
	\Session::put('locale', $locale);
	return redirect()->back();
});

Route::get('/clear-all', function () {
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('route:clear');
    Artisan::call('view:clear');
    exec('composer dump-autoload');
});

Route::group(['middleware' => 'auth'], function () {

	Route::get('/', 'HomeController@index')->name('home');
	Route::resources([
	    'employees' => 'EmployeeController'
	]);

	Route::resources([
	    'companies' => 'CompanyController'
	]);
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{!! str_replace('_', '-', app()->getLocale()) !!}">
  <head>
    <title>{{ config('app.name') }}</title>
    <meta charset="utf-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Main CSS-->
    <link rel="stylesheet" type="text/css" href="{!! asset('_admin/css/main.css') !!}">
    <!-- Font-icon css-->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- message toast css-->
    <link rel="stylesheet" href="http://izitoast.marcelodolce.com/css/iziToast.min.css">
  </head>
  <body class="app sidebar-mini rtl">
    <!-- Navbar-->
    <header class="app-header"><a class="app-header__logo" href="{!! url('/') !!}">{{ config('app.name') }}</a>
      <!-- Sidebar toggle button--><a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
      <!-- Navbar Right Menu-->
      <ul class="app-nav">
        
        <!-- User Menu-->
        @guest
        @else
        <li class="dropdown"><a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i> &nbsp; {{ Auth::user()->name }}</a>
          <ul class="dropdown-menu settings-menu dropdown-menu-right">
            <li>
              <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-sign-out fa-lg"></i> {{ __('Logout') }}</a>
              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  @csrf
              </form>
            </li>
          </ul>
        </li>
        @endguest
        
      </ul>
    </header>
    <!-- Sidebar menu-->
    <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
    <aside class="app-sidebar">
      <div class="app-sidebar__user"><img class="app-sidebar__user-avatar" src="https://s3.amazonaws.com/uifaces/faces/twitter/jsa/48.jpg" alt="User Image">
        <div>
          <p class="app-sidebar__user-name">John Doe</p>
          <p class="app-sidebar__user-designation">Frontend Developer</p>
        </div>
      </div>
      @include('layouts.menu')
    </aside>
    <main class="app-content">
        @yield('content')
    </main>
    <!-- Essential javascripts for application to work-->
    <script src="{!! asset('_admin/js/jquery-3.2.1.min.js') !!}"></script>
    <script src="{!! asset('_admin/js/popper.min.js') !!}"></script>
    <script src="{!! asset('_admin/js/bootstrap.min.js') !!}"></script>
    <script src="{!! asset('_admin/js/main.js') !!}"></script>
    <!-- The javascript plugin to display page loading on top-->
    <script src="{!! asset('_admin/js/plugins/pace.min.js') !!}"></script>
    <!-- message toast js-->
    <script src="http://izitoast.marcelodolce.com/js/iziToast.min.js" type="text/javascript"></script>
    @yield('js-content')
  </body>
</html>

resources/views/layouts/default-app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <div class="dropdown">
                          <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">{!! App::getLocale()=='en'?'English':'French' !!}
                          <span class="caret"></span></button>
                          <ul class="dropdown-menu">
                            <li><a href="{!! url('localization/en') !!}">English</a></li>
                            <li><a href="{!! url('localization/fr') !!}">French</a></li>
                          </ul>
                        </div>
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{!! app()->getLocale() !!}">
  <head>
    <title>{{ config('app.name') }}</title>
    <meta charset="utf-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Main CSS-->
    <link rel="stylesheet" type="text/css" href="{!! asset('_admin/css/main.css') !!}">
    <!-- Font-icon css-->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <header class="app-header">
      <ul class="app-nav">
        
        <!-- language Menu-->
        <li class="dropdown">
          <a class="btn btn-primary dropdown-toggle app-nav__item" type="button" data-toggle="dropdown">{!! App::getLocale()=='en'?'English':'French'  !!}
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{!! url('localization/en') !!}">English</a></li>
            <li><a class="dropdown-item" href="{!! url('localization/fr') !!}">French</a></li>
          </ul>
        </li>
        <!-- User Menu-->
        @guest        
        <li class="dropdown">
          <a class="app-nav__item" href="{{ route('login') }}"><i class="fa fa-user fa-lg"></i> &nbsp; {{ __('Login') }}</a>
        </li>
        <li class="dropdown">
          @if (Route::has('register'))
            <a class="app-nav__item" href="{{ route('register') }}"><i class="fa fa-user fa-lg"></i> &nbsp; {{ __('Register') }}</a>
          @endif
        </li>
        @else
        <li class="dropdown"><a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i> &nbsp; {{ Auth::user()->name }}</a>
          <ul class="dropdown-menu settings-menu dropdown-menu-right">
            <li><a class="dropdown-item" href="#"><i class="fa fa-cog fa-lg"></i> Settings</a></li>
            <li><a class="dropdown-item" href="#"><i class="fa fa-user fa-lg"></i> Profile</a></li>
            <li>
              <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-sign-out fa-lg"></i> {{ __('Logout') }}</a>
              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  @csrf
              </form>
            </li>
          </ul>
        </li>
        @endguest
        
      </ul>
    </header>
    <section class="material-half-bg">
      <div class="cover"></div>
    </section>
    <section class="login-content">
      <div class="logo">
        <h1>{{ config('app.name') }}</h1>
      </div>

        @yield('content')
    </section>
    <!-- Essential javascripts for application to work-->
    <script src="{!! asset('_admin/js/jquery-3.2.1.min.js') !!}"></script>
    <script src="{!! asset('_admin/js/popper.min.js') !!}"></script>
    <script src="{!! asset('_admin/js/bootstrap.min.js') !!}"></script>
    <script src="{!! asset('_admin/js/main.js') !!}"></script>
    <!-- The javascript plugin to display page loading on top-->
    <script src="{!! asset('_admin/js/plugins/pace.min.js') !!}"></script>
    <script type="text/javascript">
      // Login Page Flipbox control
      $('.login-content [data-toggle="flip"]').click(function() {
        $('.login-box').toggleClass('flipped');
        return false;
      });
    </script>
  </body>
</html>

resources/views/layouts/menu.blade.php
      <ul class="app-menu">
        <li><a class="app-menu__item active" href="{!! route('home') !!}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">@lang('dashboard.title')</span></a></li>

        <li><a class="app-menu__item active" href="{!! route('companies.index') !!}"><i class="app-menu__icon fa fa-th-list"></i><span class="app-menu__label">@lang('companies.title')</span></a></li>

        <li><a class="app-menu__item active" href="{!! route('employees.index') !!}"><i class="app-menu__icon fa fa-th-list"></i><span class="app-menu__label">@lang('employees.title')</span></a></li>
      </ul>